apiVersion: v1
kind: ConfigMap
metadata:
  name: ow-course-designer
  namespace: ow-course-designer
  labels:
    app.kubernetes.io/name: ow-course-designer
data:
  DATABASE_PROVIDER: sqlite
  DATABASE_URL: file:/app/data/prod.db
  PUPPETEER_EXECUTABLE_PATH: /usr/bin/chromium-browser
  NODE_ENV: production
  OTEL_SERVICE_NAME: ow-course-designer
